export const AUTH_TOKEN_KEY = 'AUTH_TOKEN_KEY';

export const LOGIN_SUBMITTING = 'LOGIN_SUBMITTING';
export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';
export const LOGIN_RESET = 'LOGIN_RESET';

export const FETCH_EMPLOYEES = 'FETCH_EMPLOYEES';
export const FETCH_EMPLOYEES_SUCCEEDED = 'FETCH_EMPLOYEES_SUCCEEDED';
export const FETCH_EMPLOYEES_FAILED = 'FETCH_EMPLOYEES_FAILED';

export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS';
export const FETCH_DEPARTMENTS_SUCCEEDED = 'FETCH_DEPARTMENTS_SUCCEEDED';
export const FETCH_DEPARTMENTS_FAILED = 'FETCH_DEPARTMENTS_FAILED';

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const CREATE_EMPLOYEE_SUBMITTING = 'CREATE_EMPLOYEE_SUBMITTING';
export const CREATE_EMPLOYEE_SUCCEEDED = 'CREATE_EMPLOYEE_SUCCEEDED';
export const CREATE_EMPLOYEE_FAILED = 'CREATE_EMPLOYEE_FAILED';

export const RESET_EMPLOYEE_FORM = 'RESET_EMPLOYEE_FORM';

export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const GET_EMPLOYEE_SUCCEEDED = 'GET_EMPLOYEE_SUCCEEDED';

export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const UPDATE_EMPLOYEE_SUBMITTING = 'UPDATE_EMPLOYEE_SUBMITTING';
export const UPDATE_EMPLOYEE_SUCCEEDED = 'UPDATE_EMPLOYEE_SUCCEEDED';
export const UPDATE_EMPLOYEE_FAILED = 'UPDATE_EMPLOYEE_FAILED';